#CUDA_VISIBLE_DEVICES=0 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/model_best.pth.tar --crop-size 512 --save-path ./results
#CUDA_VISIBLE_DEVICES=0 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume ./checkpoint.pth.tar --crop-size 512 --save-path ./results3
#./run/isic/deeplab-resnet/experiment_0/checkpoint.pth.tar --crop-size 512 --save-path ./results0
#CUDA_VISIBLE_DEVICES=7 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_3/checkpoint.pth.tar --crop-size 512 --save-path ./results3_p
#CUDA_VISIBLE_DEVICES=7 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_4/checkpoint.pth.tar --crop-size 512 --save-path ./results4_p
CUDA_VISIBLE_DEVICES=0 python result.py --model unet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tdpath /data/weishizheng/QiuYiqiao/ISIC-skin/ISIC2018_Task1-2_Test_Input/ --tri --resume  ./run/isic/unet/experiment_13/checkpoint.pth.tar --crop-size 512 --save-path ./pseudo_label_unet5
#CUDA_VISIBLE_DEVICES=1 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 1 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_1/checkpoint.pth.tar --crop-size 512 --save-path ./results1
#CUDA_VISIBLE_DEVICES=1 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 1 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_2/checkpoint.pth.tar --crop-size 512 --save-path ./results2
#CUDA_VISIBLE_DEVICES=1 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 1 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_3/checkpoint.pth.tar --crop-size 512 --save-path ./results3_p
#CUDA_VISIBLE_DEVICES=5 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 2 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./checkpoint.pth.tar --crop-size 512 --save-path ./results-high-confidence
#CUDA_VISIBLE_DEVICES=2 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_1/checkpoint.pth.tar --crop-size 512 --save-path ./results1
#CUDA_VISIBLE_DEVICES=2 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_2/checkpoint.pth.tar --crop-size 512 --save-path ./results2
#CUDA_VISIBLE_DEVICES=2 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_3/checkpoint.pth.tar --crop-size 512 --save-path ./results3
#CUDA_VISIBLE_DEVICES=2 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_4/checkpoint.pth.tar --crop-size 512 --save-path ./results4
#CUDA_VISIBLE_DEVICES=2 python result.py --backbone resnet --lr 0.007 --workers 1 --epochs 100 --batch-size 4 --gpu-ids 0 --checkname deeplab-resnet-tri --eval-interval 1 --dataset isic --tri --resume  ./run/isic/deeplab-resnet/experiment_5/checkpoint.pth.tar --crop-size 512 --save-path ./results5
#~/model_best.pth.tar --crop-size 512 
#~/model_best.pth.tar --crop-size 512 
#~/model_best.pth.tar --crop-size 512 
#./run/isic/deeplab-resnet/experiment_10/checkpoint.pth.tar --crop-size 512 
