CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --model unet --lr 0.007 --workers 2 --epochs 100 --batch-size 40 --gpu-ids 0,1,2,3 --checkname unet --resume ./run/isic/unet/experiment_14/checkpoint.pth.tar --eval-interval 1 --dataset isic --percent 1 --high-confidence --crop-size 512

#CUDA_VISIBLE_DEVICES=1,2 python train.py --model deeplab --backbone resnet --lr 0.007 --workers 2 --epochs 70 --batch-size 10 --gpu-ids 0,1 --checkname deeplab-resnet --eval-interval 1 --dataset pascal --percent 1 --label-percent 1  --high-confidence  --crop-size 512
#CUDA_VISIBLE_DEVICES=0, python train.py --backbone resnet --lr 0.007 --workers 2 --epochs 70 --batch-size 10 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --label-percent 1  --high-confidence  --crop-size 512
#CUDA_VISIBLE_DEVICES=0, python train.py --backbone resnet --lr 0.007 --workers 2 --epochs 70 --batch-size 10 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --label-percent 1  --high-confidence  --crop-size 512
#CUDA_VISIBLE_DEVICES=0, python train.py --backbone resnet --lr 0.007 --workers 2 --epochs 70 --batch-size 10 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --label-percent 1  --high-confidence  --crop-size 512
#CUDA_VISIBLE_DEVICES=0, python train.py --backbone resnet --lr 0.007 --workers 2 --epochs 70 --batch-size 10 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --label-percent 0.8 --crop-size 512
#CUDA_VISIBLE_DEVICES=0, python train.py --backbone resnet --lr 0.007 --workers 2 --epochs 70 --batch-size 10 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --label-percent 0.8 --crop-size 512
#CUDA_VISIBLE_DEVICES=0, python train.py --backbone resnet --lr 0.007 --workers 2 --epochs 70 --batch-size 10 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --label-percent 0.8 --crop-size 512
#CUDA_VISIBLE_DEVICES=0,1 python train.py --backbone resnet --lr 0.007 --workers 4 --epochs 70 --batch-size 14 --gpu-ids 0,1 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 0.8 --crop-size 512
#CUDA_VISIBLE_DEVICES=0,1 python train.py --backbone resnet --lr 0.007 --workers 4 --epochs 70 --batch-size 14 --gpu-ids 0,1 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --crop-size 512
#CUDA_VISIBLE_DEVICES=0 python train.py --backbone resnet --lr 0.007 --workers 4 --epochs 100 --batch-size 8 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --crop-size 512
#CUDA_VISIBLE_DEVICES=0 python train.py --backbone resnet --lr 0.007 --workers 4 --epochs 100 --batch-size 8 --gpu-ids 0 --checkname deeplab-resnet --eval-interval 1 --dataset isic --percent 1 --crop-size 512
